# Generated by Django 2.2.5 on 2020-02-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distid', models.IntegerField()),
                ('distname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hmdetails',
            fields=[
                ('hmid', models.CharField(default='test', max_length=50)),
                ('hmname', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('schoolid', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=100)),
                ('height', models.FloatField(default=1)),
                ('weight', models.FloatField(default=0)),
                ('bmi', models.FloatField(default=0)),
                ('deficency', models.TextField(default='NA')),
                ('Schoolid', models.IntegerField(default=0)),
                ('dob', models.DateField()),
                ('aadhar', models.IntegerField(default=0)),
                ('status', models.TextField(default='healthy')),
            ],
        ),
    ]
