# Generated by Django 2.2.5 on 2020-02-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Districdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distid', models.IntegerField()),
                ('distname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Studentdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bloodgroup', models.CharField(max_length=100)),
                ('Schoolid', models.IntegerField(default=0)),
                ('dob', models.DateTimeField()),
                ('aadhar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hmdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hmid', models.CharField(default='test', max_length=50)),
                ('hmname', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=100)),
                ('schoolid', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Studentdetails')),
            ],
        ),
    ]
