# Generated by Django 2.2.5 on 2020-02-29 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hmdetails',
            name='schoolid',
            field=models.IntegerField(default=0),
        ),
    ]
