# Generated by Django 2.2.5 on 2020-02-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmdetails',
            name='slug',
            field=models.SlugField(default='test'),
        ),
    ]
