# Generated by Django 2.2.5 on 2020-02-29 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=50)),
                ('dish1', models.CharField(max_length=50)),
                ('dish2', models.CharField(max_length=50)),
                ('dish3', models.CharField(max_length=50)),
                ('dish4', models.CharField(max_length=50)),
            ],
        ),
    ]
