# Generated by Django 2.2.5 on 2020-02-28 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_hmdetails_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmdetails',
            name='slug',
        ),
        migrations.AddField(
            model_name='hmdetails',
            name='hmid',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
