# Generated by Django 2.2.5 on 2020-02-29 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200229_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='hmdetails',
            name='schoolid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
