# Generated by Django 2.2.5 on 2020-02-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200229_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='slug',
            field=models.SlugField(default='test'),
        ),
    ]
