# Generated by Django 2.2.5 on 2020-02-28 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200228_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hmdetails',
            name='hmid',
        ),
    ]
