# Generated by Django 2.2.5 on 2020-02-28 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_hmdetails_hmid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hmdetails',
            name='hmid',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
